# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slaude < Formula
  desc "Claude Code ↔ Slack bridge"
  homepage "https://github.com/sttts/slagent"
  version "2026.3.9-alpha.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.6/slaude_darwin_amd64.tar.gz"
      sha256 "aec62e39b594d2598c8451a91edcfae62f6dec060678a9a294f324cf33898810"

      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.6/slaude_darwin_arm64.tar.gz"
      sha256 "f14b66d7ccc07eeb7fe8d5605794476e3eb9b1f114d0d9284089b6656c6be9fb"

      define_method(:install) do
        bin.install "slaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.6/slaude_linux_amd64.tar.gz"
      sha256 "2fb8545d0f539121680e02ab696ad69773345f591cc65b88d50c7e983860d0bd"
      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.6/slaude_linux_arm64.tar.gz"
      sha256 "53f80df8351701a04203826af18db650302734b6b9a5e4783cf84ad6fc4b66e8"
      define_method(:install) do
        bin.install "slaude"
      end
    end
  end
end
